### ISSUE TITLE
Pypi update

### ISSUE THREAD

**Issue by muffato** [gaarangoa/deeparg#1]
Hi Gustavo,

Thanks a lot for the migration and updating the _download_ mode. Are you going to update the version uploaded on pypi ? Just thinking of users who may not notice the move. Also, once pypi is updated, the Bioconda package and the Biocontainer will be automatically updated too, and I can update the Nextflow module too.

Best regards,
Matthieu

**Comment by gaarangoa** [comment]
PyPi updated (v1.0.3): https://pypi.org/project/DeepARG/

**Comment by muffato** [comment]
Wonderful ! Thank you so much !

**Comment by muffato** [comment]
@gaarangoa . `tqdm` is now only compatible with Python 3, cf https://github.com/tqdm/tqdm/pull/1439
v4.64.1 is the last version that is compatible with Python 2.

Is it something you can edit in pypi directly ? Do you need to update `setup.py` and reupload to pypi ?

**Comment by gaarangoa** [comment]
it is fixed now, let me know if it works!

**Comment by muffato** [comment]
Hi @gaarangoa ! Sorry I didn't reply sooner, I wanted to make sure it all works. We just fixed a small issue with running DeepARG with Singularity inside Nextflow, so now it's all good.

Thank you !
