### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by SelfShubham** [gaarangoa/deeparg#2]
Whenever I run deeparg I get warning message.  
Command given - deeparg predict --help
/home/ncim/anaconda3/envs/deeparg_env/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
/home/ncim/anaconda3/envs/deeparg_env/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

**Below this I get the usual help options**

**Comment by gaarangoa** [comment]
this is just a warning and shouldn't affect the results of running deeparg.
