### ISSUE TITLE
Deprecation warning and error message

### ISSUE THREAD

**Issue by izip27** [gaarangoa/deeparg#3]
Hello, 

When trying to run DeepARG I get a deprecation warning:

"DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20."

and an error message after that warning which reads:

"TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' "

I am a bit confused on how to fix this and I am following this example command:

"deeparg predict --model LS --type nucl --input /path/file.fasta --out /path/to/out/file.out"

Any help is appreciated!

**Comment by gaarangoa** [comment]
can you please share the command you are trying to use to replicate the error?

**Comment by izip27** [comment]
The command was:

deeparg predict --model LS --type nucl --input /2/scratch/batstonelab/N_adaptation_Rhizobium/Rht_long_reads/Rht_003_C.fasta --output /2/scratch/batstonelab/bin/DeepARG/deeparg/Rht_003_C

**Comment by izip27** [comment]
The command was:

deeparg predict --model LS --type nucl --input /2/scratch/batstonelab/N_adaptation_Rhizobium/Rht_long_reads/Rht_003_C.fasta --output /2/scratch/batstonelab/bin/DeepARG/deeparg/Rht_003_C

**Comment by jakubriha85** [comment]
I have the same issue:

deeparg predict --model SS --type nucl --input /home/oabi/_BioInformatika/2024_04_DeepARG_Harcov/dna-sequences.fasta --out /home/oabi/_BioInformatika/2024_04_DeepARG_Harcov/out/DeepARG_Harcov.out
/home/oabi/mambaforge/envs/deeparg_env/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
/home/oabi/mambaforge/envs/deeparg_env/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
INFO:root:DIAMOND blastx alignment
Traceback (most recent call last):
  File "/home/oabi/mambaforge/envs/deeparg_env/bin/deeparg", line 10, in <module>
    sys.exit(main())
  File "/home/oabi/mambaforge/envs/deeparg_env/lib/python2.7/site-packages/deeparg/entry.py", line 159, in main
    args.func(args)
  File "/home/oabi/mambaforge/envs/deeparg_env/lib/python2.7/site-packages/deeparg/entry.py", line 37, in predict
    '-d', args.data_path+"/database/"+args.model_version+"/features",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by izip27** [comment]
I ended up getting it to work by specifying the directory to the deeparg database!
