### ISSUE TITLE
Is the ARG-category length correct when normalizing?

### ISSUE THREAD

**Issue by wangyang1749** [gaarangoa/deeparg#4]
Hi, I found that when ARG-category is normalized [here](https://github.com/gaarangoa/deeparg/blob/b4daa15ebcc3afb792a76bae5c3d33a2947bfb59/deeparg/short_reads_pipeline/quantification/normalizationClass.py#L35), the length of ARG-category is always the length of the first gene.

```
try:
    Atype[gtype][0] += int(count)
except:
    Atype[gtype] = [int(count), geneLen]
```
```
 Xtype[itype] = (Atype[itype][0]/float(Atype[itype][1])) / \
                (float(N16s)/L16s)
```
The sorting [here](https://github.com/gaarangoa/deeparg/blob/b4daa15ebcc3afb792a76bae5c3d33a2947bfb59/deeparg/short_reads_pipeline/quantification/quantificationClass.py#L8) is only based on gene names.

```
cmd = "sort -k1,1 -k2,2n "+inputFile + "  | bedtools merge -c 12,5 -o sum,distinct >"+inputFile+".merged"
```

**Comment by gaarangoa** [comment]
The normalization is done that way for simplicity. We just need a reference to normalize to.
