### ISSUE TITLE
Question: columns in file test.clean.deeparg.align.daa.tsv

### ISSUE THREAD

**Issue by imonteroo** [gaarangoa/deeparg#5]
Hello. I have just installed and ran tets of deeparg for short reads and it worked perfectly. My question is about file test.clean.deeparg.align.daa.tsv generated. What is the meaning of each column? Thanks in advance

**Comment by gaarangoa** [comment]
this is the output from diamond alignment ([here](https://github.com/gaarangoa/deeparg/blob/b4daa15ebcc3afb792a76bae5c3d33a2947bfb59/deeparg/predict/bin/deepARG.py#L168-L178)): 

```python
                    BH[i[0]][2][8],  # alignment gene start
                    BH[i[0]][2][9],  # alignment gene end
                    i[0],  # read-id
                    i[1],  # predicted type
                    x_bh,  # best hit
                    str(i[2]),  # probability
                    BH[i[0]][2][2],  # identity
                    BH[i[0]][2][3],  # alignment length
                    BH[i[0]][2][-1],  # bitscore
                    BH[i[0]][2][-2],  # evalue
                    '1'  # count
```

**Comment by mneacsu** [comment]
Could you please be more specific about the order of the columns? It doesn't seem to match the one in the code above.
