### ISSUE TITLE
About ARG quant file

### ISSUE THREAD

**Issue by 2110537** [gaarangoa/deeparg#6]
Hello

I want to konw the meanings of each column of reads.clean.deeparg.mapping.ARG.merged.quant file,  and if there is quantification information generated that could be used for different simples comparation, like TPM/RPKM? I have many different samples, the read count data can not be used directly. 

Thanks.

**Comment by gaarangoa** [comment]
Yes, data is normalized to the abundance of 16s genes: 

from our paper:
ARGs and the relative abundance of ARGs normalized to the 16S rRNA content in the sample as used in [][]. This normalization is useful to compare the ARG content from different samples
