### ISSUE TITLE
I can't download the database

### ISSUE THREAD

**Issue by zhafrok2024** [gaarangoa/deeparg#9]
Hi! I used the DeepARG pipeline. But I can't download the database. I entered the "deeparg download_data -o data" command but the downloaded file was empty. And the website https://bench.cs.vt.edu/deeparg is also not downloadable. Can you help me? Looking forward to your reply!

**Comment by gaarangoa** [comment]
Hi Sorry for my super late reply: 

You can download the database manually from https://zenodo.org/records/8280582 

Best, 
Gustavo
